services:
  redis-cache:
    image: redis:7-alpine
    container_name: redis-cache
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: 
      - redis-server 
      - "--appendonly"
      - "yes"
      - "--maxmemory"
      - "512mb"         
      - "--maxmemory-policy"
      - "allkeys-lru"   # LRU: expulsa claves menos usadas cuando caché lleno
    # Limitar memoria es vital en la Raspberry Pi
    deploy:
      resources:
        limits:
          memory: 512M

volumes:
  redis-data:
    driver: local