FROM node:20-alpine
WORKDIR /app

# Instalar dependencias de sistema necesarias para split de archivos FLAC
RUN apk add --no-cache bash ffmpeg

COPY package*.json ./
RUN npm install
COPY . .
EXPOSE 3000
CMD ["npm", "run", "dev"]
